# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

# カスタマイズしたLinterルール
linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    cascade_invocations: false
    constant_identifier_names: true
    library_private_types_in_public_api: false
    one_member_abstracts: false
    prefer_relative_imports: true
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**/firebase_options_*.dart"
  errors:
    duplicate_ignore: ignore
    invalid_annotation_target: ignore
    invalid_use_of_visible_for_testing_member: error
    todo: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    - missing_provider_scope: false
