name: flutter_sample_flutterfire_gen
description: "flutter_sample_flutterfire_gen"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutterfire_gen_annotation:
  flutterfire_gen_utils:
  gap:
  go_router:
  json_annotation:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  flutterfire_gen:
  go_router_builder:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
